this["qwebirc"] = this["qwebirc"] || {};
this["qwebirc"]["templates"] = this["qwebirc"]["templates"] || {};

this["qwebirc"]["templates"]["about"] = Handlebars.template(function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [4,'>= 1.0.0'];
helpers = this.merge(helpers, Handlebars.helpers); data = data || {};
  var buffer = "", stack1, functionType="function", escapeExpression=this.escapeExpression;


  buffer += "<div class=\"header\">\r\n<table>\r\n<tr>\r\n<td><img src=\"images/qwebircsmall.png\" alt=\"qwebirc\" title=\"qwebirc\"/></td>\r\n<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n<td><div class=\"title\">qwebirc</div><div class=\"version\">v";
  if (stack1 = helpers.version) { stack1 = stack1.call(depth0, {hash:{},data:data}); }
  else { stack1 = depth0.version; stack1 = typeof stack1 === functionType ? stack1.apply(depth0) : stack1; }
  buffer += escapeExpression(stack1)
    + "</div></td>\r\n</tr>\r\n</table>\r\n</div>\r\n<div class=\"mainbody\">\r\nCopyright &copy; 2008-2011 Chris Porter and the qwebirc project.<br/>All rights reserved.<br/><br/>\r\nLicensed under the GNU General Public License, version 2 only.\r\n<p>\r\n<a href=\"http://www.qwebirc.org/\" target=\"_blank\">http://www.qwebirc.org/</a><br/>\r\n</p>\r\n<p>THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</p>\r\n<p>This software contains portions by the following third parties:</p>\r\n\r\n<table class=\"alignleft\" style=\"text-align: left\">\r\n<tr>\r\n<td>\r\n<li>\r\nMooTools v1.2 -- <a href=\"http://mootools.net/\" target=\"_blank\">http://mootools.net/</a><br/>\r\nCopyright &copy; 2006-2008 Valerio Proietti, MIT license.\r\n</li>\r\n<li>qwebirc icon -- <a href=\"http://meeb.org/\" target=\"_blank\">http://meeb.org/</a></li>\r\n<li>\r\nSoundManager 2 -- <a href=\"http://www.schillmania.com/projects/soundmanager2/\" target=\"_blank\">http://www.schillmania.com/projects/soundmanager2/</a><br/>\r\nCopyright &copy; 2007 Scott Schiller (schillmania.com), BSD license.\r\n</li>\r\n<li>\r\nBeep sound -- made by Dreamcast on QuakeNet.<br/>\r\nReleased into the public domain.\r\n</li>\r\n<li>\r\nMD5 implementation -- <a href=\"http://pajhome.org.uk/site/legal.html\" target=\"_blank\">http://pajhome.org.uk/site/legal.html</a>.<br/>\r\nCopyright (C) Paul Johnston 1999 - 2000, BSD license.\r\n</li>\r\n<li>\r\nBase64 functions -- <a href=\"http://www.webtoolkit.info\" target=\"_blank\">http://www.webtoolkit.info</a>.<br/>\r\nNo author name present on site.\r\n</li>\r\n</td>\r\n</tr>\r\n</table>\r\n\r\n<p>Special thanks to various comments/suggestions/hardware/bug reports from Zarjazz, Bazerka, boojah, meeb, Microbe, morphium, Starman, truff, coekie, qip, soczol, tomaw, the muppets in #rogue (hi dunks!) and everyone else I forgot :(.</p>\r\n<input type=\"button\" value=\"Close\" data-event=\"close\" class=\"btn btn-default btn-small\" />\r\n</div>";
  return buffer;
  });